### ISSUE TITLE
Trickster Boxes are invisible sometimes.

### ISSUE THREAD

**Issue by DirtyDestiny** [Eisbison/TheOtherRoles#91] opened 2021-04-21 20:47 UTC
A Player named Chris vented in Electrical Cage in and out of something, then we discovered in deadchat that he is Trickster. So sometimes Boxes seem invisible.

**Comment by survetman** [comment] 2021-04-24 10:41
We got this bug too. 
Each game there is a Trickster, he set his boxes and they were always invisible for all player (even the  trickster). But these vents are here because he could use them. We were just seeing that he went in the floor :') Furthermore, after the meeting when his boxes were placed, he got his power to light off during X sec. 
This role is working but new vents are invisible

**Comment by MrFawkes1337** [comment] 2021-04-24 11:45
maybe a sprite related issue? Unless it's intended behaviour. Can you guys post the output of your log file from BepInEx?

**Comment by EoF-1141** [comment] 2021-04-25 07:59
Should be fixed in 2.4.0

**Closed** 2021-04-26 00:02 UTC
